dist: trusty
sudo: false

language: node_js
node_js:
  - '14'

cache:
  directories:
    - .frontend/node_modules

before_install: cd frontend

install:
  - npm install

before_script: cd frontend

script:
  - npm test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
