language: node_js
node_js:
  - '14'
dist: trusty
sudo: required
addons:
  chrome: stable
notifications:
  email:
    on_success: never
    on_failure: always
before_script:
  - cd frontend
script:
  - npm install
  - npm run test:travis
before_deploy:
  - npm run build
  - npm install netlify-cli -g
cache:
  - node_modules
  - netlify-cli
deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=dist/frontend --prod
  on:
    branch: master
