export const stud1 = {
    name: 'primo',
    surname: 'primi',
    parent: {
      name: 'padre',
      surname: 'padri',
      phoneNumber: 0,
      fiscalCode: null,
      address: null,
    },
    receipts: [],
    dateOfBirth: '2021-07-11T22:00:00.000Z',
    phoneNumber: 0,
    fiscalCode: null,
    schoolClass: null,
    address: null,
    notes: '',
    id: '60fedd5892d0714954a2ab57',
  },
  stud2 = {
    name: 'primo',
    surname: 'primi',
    parent: {
      name: 'padre',
      surname: 'padri',
      phoneNumber: 0,
      fiscalCode: null,
      address: null,
    },
    receipts: [],
    dateOfBirth: null,
    phoneNumber: 0,
    fiscalCode: null,
    schoolClass: null,
    address: null,
    notes: '',
    id: '60fedd5892d0714954a2ab57',
  },
  stud3 = {
    name: 'primo',
    surname: 'primi',
    parent: {
      name: 'padre',
      surname: 'padri',
      phoneNumber: null,
      fiscalCode: null,
      address: 'abcde',
    },
    receipts: [],
    dateOfBirth: null,
    phoneNumber: null,
    fiscalCode: 'chrndr94m11c621q',
    schoolClass: null,
    address: 'abcde',
    notes: '',
    id: '60fedd5892d0714954a2ab57',
  },
  stud4 = {
    name: 'primo',
    surname: 'primi',
    parent: {
      name: 'padre',
      surname: 'padri',
      phoneNumber: 0,
      fiscalCode: null,
      address: 'abcde',
    },
    receipts: [],
    dateOfBirth: null,
    phoneNumber: null,
    fiscalCode: 'chrndr94m11c621q',
    schoolClass: null,
    address: 'abcde',
    notes: '',
    id: '60fedd5892d0714954a2ab57',
  };
